replicaCount: 3

containers:
  - name: nginx
    image:
      repository: nginx
      tag: latest
    ports:
      - containerPort: 80
    env:
      - name: ENVIRONMENT
        value: production
      - name: LOG_LEVEL
        value: info
    volumeMounts:
      - name: html-volume
        mountPath: /usr/share/nginx/html

  - name: sidecar
    image:
      repository: busybox
      tag: latest
    command: ["sleep", "3600"]

volumes:
  - name: html-volume
    enabled: true
    emptyDir: {}

service:
  enabled: true
  type: ClusterIP
  port: 80

enableHtmlConfig: true
